CREATE TABLE CLUSTERING_STATUS(
    BOT_ID VARCHAR NOT NULL ,
    IS_COMPLETED VARCHAR(10),
    PROGRESS DECIMAL(3, 2),
    TS TimeStamp
);

CREATE TABLE TERM_FREQUENCY(
    BOT_ID VARCHAR NOT NULL,
    TERM VARCHAR(50),
    DF DECIMAL(3, 2),
    TS TimeStamp
);

CREATE TABLE CH(
    BOT_ID VARCHAR NOT NULL,
    CH DECIMAL(4, 2),
    TS TimeStamp
);

CREATE TABLE CLUSTERS(
    BOT_ID VARCHAR NOT NULL,
    CLUSTER_ID INTEGER,
    VOLUME INTEGER,
    TS TimeStamp
);

CREATE TABLE CLUSTER_KEYWORDS(
    BOT_ID VARCHAR NOT NULL,
    CLUSTER_ID INTEGER,
    KEYWORDS VARCHAR(65532),
    TFIDF DECIMAL(3, 2),
    TS TimeStamp
);

CREATE TABLE CLUSTER_SAMPLES(
    BOT_ID VARCHAR NOT NULL,
    CLUSTER_ID INTEGER,
    SAMPLE VARCHAR(65532),
    TS TimeStamp
);
