create database BOOSTDB;

use BOOSTDB;

CREATE TABLE CONVS (
    CONV_ID INT PRIMARY KEY NOT NULL,
    BOT_ID VARCHAR(32) NOT NULL,
    CONV VARCHAR(1024) NOT NULL,
    TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE WORDS (
    WORD_ID INT PRIMARY KEY NOT NULL,
    BOT_ID VARCHAR(32) NOT NULL,
    WORD VARCHAR(32) NOT NULL,
    DF DECIMAL(4, 2) NOT NULL,
    TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE TFIDFS (
    TFIDF_ID INT PRIMARY KEY NOT NULL,
    BOT_ID VARCHAR(32) NOT NULL,
    CONV_ID INT NOT NULL ,
    WORD_ID INT NOT NULL,
    TFIDF DECIMAL(4, 2) DEFAULT 0.0,
    TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY(CONV_ID) REFERENCES CONVS(CONV_ID),
    FOREIGN KEY(WORD_ID) REFERENCES WORDS(WORD_ID)
);

CREATE TABLE CLUSTERING_STATUS(
    BOT_ID VARCHAR(32) PRIMARY KEY NOT NULL,
    IS_COMPLETED INT DEFAULT 0,
    PROGRESS DECIMAL(4, 2) DEFAULT 0.0,
    TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
